const questions = [
  'What is the title of your event?',
  'What is the date and time for your event?',
  'What is the duration for your event?',
  'What kind of event is this?',
  'What is the name of the venue for your event?',
  'What is the street address of the venue for your event? -> (approve map search)',
  'What time do the doors open to the public?',
  'When does the venue open for the performers?',
  'Who is the headliner?',
  'What is the headliner\'s website?',
  'Are there promotional websites?',
  'How many opening acts?',
  'How many stages will you have?',
  'What is the name of stage number 1?',
  'How does the venue describe this stage?',
  'How does the venue describe the location of this stage/How do yu get there from the front door?',
  'What type of stage is this?',
  'What are the dimensions of the stage in imperical measuremnts (length, width, depth, hight)?',
  'What are the dimensions of the stage in metric (length, width, depth, hight)?',
  'How many seating sections does this venue have? ',
  'Location of the venue\'s seating map (for example https://turinglimited.com/assets/brand/stadium-svgrepo-com.svg): ',
  'Location of the ticket art (for example https://turinglimited.com/assets/brand/event-poster-with-white-details-svgrepo-com.svg): ',
];
